import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const today = new Intl.DateTimeFormat("es-ES", { dateStyle: "long" }).format(new Date());
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <header className="fixed top-0 left-0 w-full z-40 bg-background/50 backdrop-blur-sm border-b">
          <div className="max-w-7xl mx-auto w-full h-16 flex items-center px-4">
            <h1 className="text-2xl font-bold">
              <Link href="/listar" className="hover:underline focus:outline-none focus:ring-2 focus:ring-ring rounded-sm">
                Mi App
              </Link>
            </h1>
          </div>
        </header>
        <main className="flex-1 pt-16 pb-28">
          {children}
        </main>
        <footer className="fixed bottom-0 left-0 w-full p-4 border-t text-center bg-background/60 backdrop-blur-md z-50">
          <p className="text-sm text-gray-500">© 2025 My App. Hoy es {today}. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
