import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentYear = new Date().getFullYear();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`} >
        <header className="fixed inset-x-0 top-0 z-50 border-b bg-background/90 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 items-center justify-between">
            <Button variant="ghost" asChild className="px-0">
              <Link href="/" className="flex items-center gap-2 text-base font-semibold">
                <Image src="/next.svg" alt="Logo" width={100} height={24} priority />
                <span className="hidden text-sm font-medium uppercase text-muted-foreground sm:inline">Inicio</span>
              </Link>
            </Button>
          </div>
        </header>
        <main className="container pt-16 pb-24">
          {children}
        </main>
        <footer className="fixed inset-x-0 bottom-0 border-t bg-background/90 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-12 items-center justify-center text-sm text-muted-foreground">
            © {currentYear} Tu Empresa. Todos los derechos reservados.
          </div>
        </footer>
      </body>
    </html>
  );
}
